baseURL = 'https://y30n9ju1v.github.io/'
languageCode = 'en-us'
title = "y30n9ju1v's Blog"
theme = "PaperMod"

[[menu.main]]
name = "Archives"
url = "/archives/"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
  ShowToc = true

  [params.homeInfoParams]
  Title = "Hi there 👋 "
  Content = "📧 : y30n9ju1v [at] 9mail [dot] com"
